### PR TITLE
Shapefile area averaging

### PR DESCRIPTION
**Pull request by rhattersley**

### CODE REVIEW

**Comment by rhattersley** [comment]
Hi @dkillick - I've rebased so it should be ready to go.

**Comment by DPeterK** [comment]
Oh, I also made a few changes based on @cpelley's PR, which I suspect you might not have picked up so I still can't merge...

**Comment by rhattersley** [comment]
OK - rebased again. Fingers crossed! :wink:

**Comment by DPeterK** [comment]
Nice! Thanks @rhattersley :smile:

**Pull request merged**
